[project]
site_name = "straysheep.dev"
#site_url = "http://127.0.0.1:8000"
site_url = "https://straysheep-dev.github.io"
repo_url = "https://github.com/straysheep-dev/straysheep-dev.github.io"
repo_name = "straysheep-dev.github.io"
copyright = "Copyright &copy; 2018-2025 straysheep-dev"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/straysheep-dev"

[[project.extra.social]]
icon = "fontawesome/brands/gitlab"
link = "https://gitlab.com/straysheep-dev"

[[project.extra.social]]
icon = "simple/ansible"
link = "https://galaxy.ansible.com/ui/standalone/namespaces/22091/"

[[project.extra.social]]
icon = "fontawesome/brands/discord"

[[project.extra.social]]
icon = "simple/hackthebox"

[[project.extra.social]]
icon = "simple/tryhackme"
link = "https://tryhackme.com/p/straysheep.dev"

[[project.extra.social]]
icon = "material/key"
link = "https://github.com/straysheep-dev/public-keys"

[project.theme]
name = "material"
logo = "assets/logo.svg"
favicon = "assets/favicon.svg"
font.text = "Roboto"
font.code = "Roboto Mono"
plugins = [
    "search",
    "social"
]
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.path",
    "navigation.tabs",
    "navigation.sections",
#    "navigation.indexes",
    "navigation.expand",
    "navigation.path",
    "navigation.top",
    "toc.integrate",
    "toc.follow",
    "search.suggest",
    "search.highlight",
    "search.share",
    "content.tooltips"
]

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "orange"
scheme = "default"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "indigo"
scheme = "slate"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to light mode"

[project.markdown_extensions]
[project.markdown_extensions.attr_list]
[project.markdown_extensionsmd_in_html]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = "true"
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
