[project]
site_name = "straysheep.dev"
#site_url = "http://127.0.0.1:8000"
site_url = "https://straysheep-dev.github.io"
repo_url = "https://github.com/straysheep-dev/straysheep-dev.github.io"
repo_name = "straysheep-dev.github.io"
copyright = "Copyright &copy; 2018-2025 straysheep-dev"

# Specifiying nav patterns here controls how they appear and in what order
# This also allows you to "hide" sections that do not need to appear in the nav bar
nav = [
  {"Main" = "index.md"},
  {"Resources" = "resources.md"},
  {"Notes" = [
    "notes/about.md",
    "notes/aide.md",
    "notes/ansible.md",
    "notes/ansible-molecule.md",
    "notes/art-x-uac.md",
    "notes/bind9.md",
    "notes/bitwarden.md",
    "notes/check-auditd-demo.md",
    "notes/cicd.md",
    "notes/clipboard-snooping.md",
    "notes/compile-static-binaries.md",
    "notes/custom-shell-profiles.md",
    "notes/flatpak.md",
    "notes/kvm.md",
    "notes/linting.md",
    "notes/migrating-to-zensical.md",
    "notes/nessus.md",
    "notes/netcat-seh-rce.md",
    "notes/network-commands.md",
    "notes/nzyme-rpi-proxmox-tailscale.md",
    "notes/openscap.md",
    "notes/openwrt.md",
    "notes/pfsense.md",
    "notes/powerstig.md",
    "notes/proxmox.md",
    "notes/rsync.md",
    "notes/snap.md",
    "notes/wazuh-tailscale.md",
    "notes/wifichallenge-review.md",
    "notes/windows.md"
  ]},
  {"License" = "license.md"}
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/straysheep-dev"

[[project.extra.social]]
icon = "fontawesome/brands/gitlab"
link = "https://gitlab.com/straysheep-dev"

[[project.extra.social]]
icon = "simple/ansible"
link = "https://galaxy.ansible.com/ui/standalone/namespaces/22091/"

[[project.extra.social]]
icon = "fontawesome/brands/discord"

[[project.extra.social]]
icon = "simple/hackthebox"

[[project.extra.social]]
icon = "simple/tryhackme"
link = "https://tryhackme.com/p/straysheep.dev"

[[project.extra.social]]
icon = "material/key"
link = "https://github.com/straysheep-dev/public-keys"

[project.theme]
name = "material"
custom_dir = "overrides"
#logo = "assets/logo.svg"
favicon = "assets/favicon.svg"
font.text = "Roboto"
font.code = "Roboto Mono"
plugins = [
    "search",
    "social"
]
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.path",
    "navigation.tabs",
    "navigation.sections",
    "navigation.expand",
    "navigation.path",
    "navigation.top",
    "toc.integrate",
    "toc.follow",
    "search.suggest",
    "search.highlight",
    "search.share",
    "content.tooltips"
]

[project.theme.icon]
logo = "straysheep-dev/logo"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "orange"
accent = "orange"
scheme = "default"
toggle.icon = "material/toggle-switch"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "orange"
accent = "orange"
scheme = "slate"
toggle.icon = "material/toggle-switch-off-outline"
toggle.name = "Switch to light mode"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
options.custom_icons = ["overrides/.icons"]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = "true"
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
